### PR TITLE
Using vcpkg

### PR DESCRIPTION
**Pull request by nfarid**
Vcpkg's manifest mode is used handle the dependencies and removed all the vendoring.
A library alias is added which is "vili::vili".
Install commands are added to the cmake script to make this project installable.
A package config file is added so it can be found via find_package.
There's some other miscellaneous things too.

The eventually goal is to port this library to vcpkg as well.

### CODE REVIEW

**Comment by Sygmei** [comment]
Awesome PR :)
Would it be possible to fix the CI ?

**Comment by nfarid** [comment]
Github actions now reports this as a success.

https://github.com/nfarid/Vili/actions/runs/3420632110

**Comment by nfarid** [comment]
@Sygmei, I have squashed my commits into just 4:  
- Editing the gitignore.
- Using vcpkg.
- Removing the vendored libraries.
- Making the library installable.

**Review by Sygmei — APPROVED** [review]
Approved 👍 thanks a lot for your contribution !

**Pull request merged**
